### ISSUE TITLE
As a developer, I want to initialize the database using dependency injection so that I can have a modular and testable database setup.

### ISSUE THREAD

**Issue by therobertcrocker** [therobertcrocker/wayfinder#1]
**Tasks (TDD Loop):**
  - [ ] **Test Phase:** Write a failing test to ensure that the database can be initialized without errors using the `DataManager` interface. 
  - [ ] **Implementation Phase:** 
     - [ ] Define the `DataManager` interface.
     - [ ] Implement the `BboltDataManager` struct.
     - [ ] Run the test to ensure it now passes with the new implementation.
  - [ ] **Refactor Phase:** Review and refactor the code to ensure it's clean, readable, and maintainable.
